### ISSUE TITLE
Team 254 Vision Talk

### ISSUE THREAD

**Issue by LudingtonRobotics** [LimelightVision/LimelightDocs#12]
Minor issue but the URL for the 254 vision talk on this page:
http://docs.limelightvision.io/en/latest/additional_resources.html
is not correct.
You have:
https://www.youtube.com/watch?v=rLwOkAJqlmo
And it is:
https://www.youtube.com/watch?v=rLwOkAJqImo
It should be a capital i and you have a lower case L in the 3 from the last position.

**Comment by bhjelstrom** [comment]
Fixed, thank you!
