### ISSUE TITLE
Framerate locking up while driving.

### ISSUE THREAD

**Issue by zosowski** [LimelightVision/LimelightDocs#13]
Limelight 2, newest update. 

When driving the robot aggressively, the limelight will reliably stop updating frames and "hang". The green light on the limelight goes solid when it hangs. It will hand for a few seconds then come back. While not hanging, it remains at a solid 85-90fps.

**Comment by bhjelstrom** [comment]
Hi, are you using 2019.3, or 2019.4?

**Comment by AlexanderDefuria** [comment]
Hello, I'm having the same issue has there been any fix to it?

**Comment by zosowski** [comment]
It was happening on 2019.1 so we updated to 2019.4 where the issue is still present.

**Comment by bhjelstrom** [comment]
Can you two post the .vpr pipeline files that cause this to happen? You can retrieve the files by clicking the "Download" button at the top of the web interface.

**Comment by bhjelstrom** [comment]
Also, please post here or send a support email with the following:
* Electrical setup
* Information regarding any attached USB cameras
* Steps that may reproduce the issue

**Comment by bhjelstrom** [comment]
Closing this. There were multiple causes of hangs, and all have been resolved.
