### ISSUE TITLE
2019 Left Eyebrow Target Model Download Incorrect

### ISSUE THREAD

**Issue by alexanderswerdlow** [LimelightVision/LimelightDocs#14]
The 2019 Left Eyebrow Target Model link downloads the Dual Target model.

**Comment by anherrera** [comment]
I was able to open the dual target file, delete rows 5-6, and re save it as a left eyebrow model. Just to get you un stuck for the meantime.

**Comment by anherrera** [comment]
Seems to work when I use the first four rows of the dual target csv as the model. As long as the contour filtering directions are correct

**Comment by bhjelstrom** [comment]
Resolved, thanks!
