### ISSUE TITLE
Python NetworkTable API docs have redundant semicolon

### ISSUE THREAD

**Issue by DGKSK8LIFE** [LimelightVision/LimelightDocs#19]
In the first python code block, at https://docs.limelightvision.io/en/latest/networktables_api.html, there is a semicolon terminating a method call. This is redundant and not official python syntax.
![image](https://user-images.githubusercontent.com/45473363/105200199-3198e580-5b05-11eb-8241-00bac8f54196.png)

**Comment by bhjelstrom** [comment]
Thanks!
