### ISSUE TITLE
Saving frames from camera stream during match for tuning HSV values

### ISSUE THREAD

**Issue by GrantPerkins** [LimelightVision/LimelightDocs#2]
Hi Limelight staff, love your product!

[My frc team ](https://github.com/Team1100) just bought a Limelight this year, and we're really excited to start using it. However, one thing we want to do is to be able to save frames from the camera stream during the match, when we detect contours. We want to do this in order to tune the HSV values for the lighting at the competitions. Our code is in Java.

We are having a lot of trouble doing this, however. We understand we could bring a laptop onto the field before the match and tune it then, but we'd prefer to not have to do that. So far, we've attempted to use OpenCV to access the stream, but have had problems with recognizing the stream in the code.

How could we save frames from the stream?

Our code:

```
import org.usfirst.frc.team1100.robot.subsystems.vision.Limelight;

import org.opencv.videoio.VideoCapture;
import org.opencv.core.Mat;
import org.opencv.imgcodecs.Imgcodecs;

import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

/**
 * Attempt at capturing images using OpenCV
 */
public class CaptureImage extends Command {

        //Only save one image per match
	boolean imageCaptured = false;
	Limelight lime;
	VideoCapture camera;
	Mat frame;
	
    public CaptureImage() {
        requires(Limelight.getInstance());
    }

    protected void initialize() {
        //Attempts to open stream
    	camera = new VideoCapture("http://10.11.00.11:5800");
    	frame = new Mat();
    	lime = Limelight.getInstance();
    }

    protected void execute() {
    	if (lime.contoursDetected() && !imageCaptured) {
    		if (camera.read(frame)) { //Always returns false
                        //Writes Output.jpg to roborio, but always is blank
	    		Imgcodecs.imwrite("/home/lvuser/Images/Output.jpg", frame);
	    		imageCaptured = true;
    		} else {
    			SmartDashboard.putBoolean("Open", camera.isOpened()); //Always false
    		}
    	}
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
    	SmartDashboard.putBoolean("Image Captured", imageCaptured); //Always false
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
```

**Comment by desertgreg** [comment]
Hi Grant!  We are actually working on the feature you describe only the limelight will store your images and thus they would be full quality uncompressed images.   Brandon will chime in with more details!

Greg

**Comment by GrantPerkins** [comment]
Well, we figured out how to save images from the Limelight camera stream. Looking forward to the new feature! https://github.com/Team1100/FRCPowerUp/blob/dev/src/org/usfirst/frc/team1100/robot/commands/vision/SaveCubePNG.java
