### ISSUE TITLE
Possible Signage Error in Aiming Using Vision Case Study

### ISSUE THREAD

**Issue by vmalepati1** [LimelightVision/LimelightDocs#20]
The case study states: "If the error is bigger than some threshold, just add a constant to your motor command which roughly represents the minimum amount of power needed for the robot to actually move (you actually want to use a little bit less than this)."

Currently this logic is implemented by the following conditional statements:

```java
if (tx > 1.0)
{
        steering_adjust = Kp*heading_error - min_command;
}
else if (tx < 1.0)
{
        steering_adjust = Kp*heading_error + min_command;
}
```

Basically what I interpreted this to mean is that when |tx| > threshold, add some minimum command to make the mechanism rotate in the correct direction and exceed static friction.

With the current code the conditional statements will work fine when tx is positive because when tx > 1.0, we will subtract the minimum command. The conditional statements will also work fine when tx is negative and less than -1.0 because we will add the minimum command. The problem is that the condition ```tx < 1.0``` is **too** inclusive. For example when the tx is -0.5, which is "smaller" than the threshold of one degree, the minimum command will be in effect. However, when the tx is 0.5, the minimum command will not be in effect. I am wondering if this is intentional, or the code was intended to be written as the following:

```java
if (Math.abs(tx) > 1.0) {
	if (tx < 0) {
		steering_adjust = Kp*heading_error + min_command;
	} else {
		steering_adjust = Kp*heading_error - min_command;
	}
} else {
	steering_adjust = Kp*heading_error;
}
```

**Comment by bhjelstrom** [comment]
Finally fixed, thank you
