### ISSUE TITLE
Unable to connect to Limelight unless using static IP on roboRIO

### ISSUE THREAD

**Issue by jonahsnider** [LimelightVision/LimelightDocs#21]
My team and I have been having connection issues on our Limelight 2+ and recently discovered the solution.
I'm sharing what worked for us in this issue to help other teams experiencing the same issue and to bring the issue to your attention.

## Prerequisites

- A fresh Limelight 2+ flashed with v2020.4 (hardware version may not matter)
- roboRIO v1 flashed with the initial 2022 version
- Open-Mesh router flashed with the initial 2022 version 

You turn on your robot and observe that every component successfully starts.
The Limelight fans turn on, blinks its lights, etc.

## Problem

- The Limelight finder can't detect the device
- `limelight.local:5801` does not resolve
- There are no Limelight entries in NetworkTables

## Solution

1. Go to your roboRIO's configuration page at `http://10.TE.AM.2`
2. Set the IP to static ([docs](https://docs.wpilib.org/en/stable/docs/networking/networking-introduction/ip-configurations.html#in-the-pits-static-configuration))
   	These instructions may not be applicable when at an FRC tournament
3. Power cycle Limelight, roboRIO, and router
4. The Limelight finder should now work

I'm not sure if this issue is caused by a misconfiguration on our part or if this is unexpected behavior from the Limelight.

**Comment by AsianVy** [comment]
Closed by 30ed2e0ada2a2ccf485c1b209f870cec746754b4

**Comment by jonahsnider** [comment]
Closed by 30ed2e0ada2a2ccf485c1b209f870cec746754b4
