### ISSUE TITLE
Marker size settings in April Tag sections of docs resulting in incorrect distances

### ISSUE THREAD

**Issue by nihonjinrxs** [LimelightVision/LimelightDocs#25]
We've been testing the new 2023.0.1 build of the Limelight software on our Limelight 2+ against April Tag targets for this year's FRC season game.

In doing so, we've found that the recommended value for marker size, 203.2 mm (8 inches), seems to result in distance and position calculations that are off by about a third. That value seems to correspond to a measurement of the target including the white border surrounding it. If we instead set the marker size to 152.4 mm (6 inches), which corresponds to the size of the marker from black edge to black edge, excluding the white border, we get accurate distance and positioning measurements.

Is there some configuration we should change to make this work with the recommended value, or should that value be corrected to exclude the 1 inch thick white border on the markers?

**Comment by bhjelstrom** [comment]
You are correct. Thanks for taking the time to report this! https://www.chiefdelphi.com/t/limelight-2023-1-megatag-performance-boost-my-mistake/423943
