### ISSUE TITLE
New GUI features not in documentation

### ISSUE THREAD

**Issue by gearsincorg** [LimelightVision/LimelightDocs#3]
Hi

I'm trying to get up to speed with Limelight and trying to work with cubes rather than Retro-Reflectors.
So colors matter....

These were added earlier this year...

Red-Balance slider
Blue-Balance slider
Better default color balance settings

Can they be discussed in the online docs please?  
eg: How should we be using them?

Thanks
Phil.

**Comment by desertgreg** [comment]
Those just let you adjust the white balance.  One way is to hold something white in front of the camera and tune the sliders until it looks white.  We exposed the sliders just in case someone finds it useful to skew the colors when tracking certain colors (like cubes).  We did not end up using that idea ourselves.

We do need to update the website. 

Greg

**Comment by gearsincorg** [comment]
OK.  I see.

After experimenting with the color balance, is there a way to get back to the "defaults"?  
ie: What are the better default values?

**Comment by bhjelstrom** [comment]
Hey Phil,

The default blue balance is 1975, and the default red balance is 1200.
Color "balances" basically control the intensity of certain colors.
Increasing the blue balance, for example, will increase the intensity of
the blue components of your image.

It seems like the "best" settings can vary per camera, but I would
recommend increasing the blue balance to make your image less yellow. If
you've ever turned on a blue-light filter on your phone/pc, you might
notice that everything gets a bit closer to yellow (bad for tracking yellow
cubes). This should really help your thresholding pick-out cubes more
easily. Let me know if this helps!

Best,
Brandon

**Comment by gearsincorg** [comment]
Thanks
