### ISSUE TITLE
What algorithm do you apply to generate a list of contours?

### ISSUE THREAD

**Issue by abhijit-c** [LimelightVision/LimelightDocs#6]
Hey all, great project you have here, it's saving my FRC team a lot of time messing with vision.

I was reading through the documentation, and found in the Vision Pipeline Tuning Section, under the Contour Filtering, you have the line:

    "After thresholding, Limelight applies a .... to generate a list of contours."

What exactly do you apply here? We ask, because we are interested in trying to possible select a hull that isn't necessarily the largest and are interested in the process.

[Here's a link to the exact section in the github.](https://github.com/LimelightVision/LimelightDocs/blob/master/docs/vision_pipeline_tuning.rst#contour-filtering)

**Comment by bhjelstrom** [comment]
Hey, you can navigate to the contour tab to change the filtering process. You can select sort modes like largest, leftmost, closest, etc. Does this help?
![image](https://user-images.githubusercontent.com/13728935/51659927-f2108080-1f60-11e9-82b9-56fd1fa22d72.png)
