### ISSUE TITLE
Conflicting instructions for imaging of Limelight v1

### ISSUE THREAD

**Issue by rzblue** [LimelightVision/LimelightDocs#9]
On the getting started page of the documentation the Limelight 1 tab of the imaging instructions tells users to "Apply power to your limelight" directly after plugging in the usb cable. However, the warning underneath instructs "Only connect the microUSB cable while imaging." When imaging a Limelight 1, which instructions should be used?

**Comment by bhjelstrom** [comment]
I think this has been resolved. LL1 requires external power, and LL2 does not require external power. Thank you!
